name: Run RSpec tests
on: [pull_request]
jobs:
  run-rspec-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Run tests
        run: |
          bundle exec rspec
      - name: Add code coverage comment
        uses: romeovs/lcov-reporter-action@v0.2.11
        with:
          lcov-file: ./coverage/lcov/ruby-simplecov-workflow.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
