name: Run RSpec tests
on: [pull_request]
jobs:
  run-rspec-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rspec
      - name: Add code coverage comment
        uses: Nef10/lcov-reporter-action@v0.3.0
        with:
          lcov-file: ./coverage/lcov/ruby-simplecov-workflow.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
